easy_admin:
  entities:
    # List the entity class name you want to manage
    #        - App\Entity\Product
    #        - App\Entity\Category
    - App\Entity\User
    - App\Entity\Recipe
    - App\Entity\Ingredient
    - App\Entity\Measure
    - App\Entity\RecipeIngredient
